### ISSUE TITLE
undefined method `get_videos' for KhanAcademy::Topic:Class

### ISSUE THREAD

**Issue by jforaker** [abigezunt/RubyKhan#1]
happens with: 
    humanities = KhanAcademy::Topic.get_videos('humanities')

**Comment by abigezunt** [comment]
So this has to do with the way their API is set up and I haven't figured out a way around it. Their topics are set up like a tree and there are only videos and exercises for the end-points of the tree. Humanities is a broad topic that doesn't have videos associated with it, only sub-topics and sub-sub-topics. It's unfortunately hard to predict which topics will have videos and which will return an error - I agree that I should go back in there and protect against returning an error and instead return an empty array or something. Thanks for the suggestion.
